# Nominal Encoding

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [40]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [41]:
df=pd.read_csv("/content/drive/MyDrive/cars (1).csv")

In [42]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [43]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [44]:
x=df.drop(columns='selling_price')
y=df['selling_price']

In [45]:
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [46]:
y

0       450000
1       370000
2       158000
3       225000
4       130000
         ...
8123    320000
8124    135000
8125    382000
8126    290000
8127    290000
Name: selling_price, Length: 8128, dtype: int64

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

#3.OneHotEncoding

## 🔹 What is One-Hot Encoding?

**One-Hot Encoding (OHE)** is a **data preprocessing technique** used in **Machine Learning** to convert **categorical (text) data** into **numerical (binary) form**, so that ML models can understand it.

---

## ❓ Why Do We Need One-Hot Encoding?

Most machine learning algorithms **cannot work with text** like:

```
Color = Red, Blue, Green
City = Karachi, Lahore, Islamabad
```

They only understand **numbers**.

👉 One-Hot Encoding solves this problem by creating **binary (0/1) columns** for each category.

---

## 📌 Simple Example

### Original Data

```
Color
Red
Blue
Green
```

### After One-Hot Encoding

```
Red   Blue   Green
1      0       0
0      1       0
0      0       1
```

✔ Each category gets its own column
✔ Only one column has `1` → that’s why it’s called **one-hot**

---

## 🧠 Why It Is Called “One-Hot”?

Because:

* **One value = 1 (hot)**
* **All others = 0 (cold)**

Example:

```
Blue → [0, 1, 0]
```

---

## 🚀 Real-World Example (ML)

### Dataset

```
City        Price
Karachi     50
Lahore      45
Islamabad   60
```

### After One-Hot Encoding

```
Karachi  Lahore  Islamabad  Price
1        0       0           50
0        1       0           45
0        0       1           60
```

Now ML models can **learn patterns correctly**.

---

## ⚠️ Dummy Variable Trap (Important)

If we create **all columns**, one column can be predicted from others → causes **multicollinearity**.

### Solution:

Drop one column

Example:

```
Karachi  Lahore
1        0   → Islamabad
0        1   → Lahore
0        0   → Karachi
```

This is why we often use:

```python
OneHotEncoder(drop='first')
```

---

## 🆚 One-Hot Encoding vs Label Encoding

| Feature       | One-Hot Encoding | Label Encoding            |
| ------------- | ---------------- | ------------------------- |
| Best for      | Nominal data     | Ordinal data              |
| Order matters | ❌ No             | ✅ Yes                     |
| Example       | City, Color      | Grade (Low, Medium, High) |

---

## ✅ When to Use One-Hot Encoding?

✔ Nominal categorical data
✔ Linear Regression
✔ Logistic Regression
✔ Neural Networks

❌ Not ideal for:

* Very high-cardinality features (many categories)
* Tree-based models (Random Forest, Decision Tree)

---

## 🧾 One-Line Definition (Exam-Ready)

> **One-Hot Encoding is a technique used to convert categorical variables into binary numerical columns so that machine learning models can process them effectively.**

In [48]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [50]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])

In [51]:
x_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [52]:
x_train_new.shape

(6502, 7)

In [53]:
x_test_new=ohe.fit_transform(x_test[['fuel','owner']])

In [54]:
x_test_new

array([[1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [55]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 83000, 0, ..., 0, 0, 0],
       ['Tata', 110000, 0, ..., 1, 0, 0],
       ['Hyundai', 83000, 1, ..., 0, 0, 1],
       ...,
       ['Skoda', 116000, 1, ..., 0, 0, 0],
       ['Mahindra', 200000, 1, ..., 0, 0, 0],
       ['Tata', 110000, 1, ..., 0, 0, 1]], dtype=object)

# Most Frequent Categories

In [56]:

counts=df['brand'].value_counts()

In [57]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [58]:
df['brand'].nunique()

thresold=100

In [59]:
repl=counts[counts>=thresold].index

In [60]:
df = df[df["brand"].isin(repl)]

In [61]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [62]:
df['brand'].value_counts()

brand
Maruti        2448
Hyundai       1415
Mahindra       772
Tata           734
Toyota         488
Honda          467
Ford           397
Chevrolet      230
Renault        228
Volkswagen     186
BMW            120
Skoda          105
Name: count, dtype: int64