# What is Ecoding? & Types of Encoding


# **1. What is Encoding in Machine Learning?**

**Encoding** is the process of **converting categorical (text or label) data into numerical form** so that **machine learning algorithms can understand and process it**.

👉 ML models **cannot work directly with text or categories** because they perform **mathematical calculations**.

---

### **Example (Raw Data)**

| City      |
| --------- |
| Karachi   |
| Lahore    |
| Islamabad |

❌ ML model cannot process text like *Karachi*, *Lahore*.

✔ We must convert them into **numbers → Encoding**

---

# **2. Why Encoding Is Important?**

### **1️⃣ ML models only understand numbers**

Algorithms use:

* Addition
* Multiplication
* Distance
* Gradients

Text data must be converted to numeric form.

---

### **2️⃣ Enables mathematical calculations**

Distance-based and gradient-based algorithms require numbers.

---

### **3️⃣ Prevents wrong relationships**

Wrong encoding can introduce **false order or bias**.

---

### **4️⃣ Improves model performance**

Correct encoding improves:

* Accuracy
* Training stability
* Convergence speed

---

# **3. Types of Encoding (Explained in Detail)**

---

## **1️⃣ Label Encoding**

### **Definition**

Each category is assigned a **unique integer value**.

### **Example**

| City      | Encoded |
| --------- | ------- |
| Karachi   | 0       |
| Lahore    | 1       |
| Islamabad | 2       |

### **Advantages**

✔ Simple
✔ Memory efficient

### **Disadvantages**

❌ Introduces **false order** (Islamabad > Lahore > Karachi)

### **Best Used For**

* **Ordinal data** (ranking exists)
* Target variables (Yes/No)

### **Example (Ordinal)**

| Education | Label |
| --------- | ----- |
| Matric    | 0     |
| Inter     | 1     |
| Bachelor  | 2     |
| Master    | 3     |

---

## **2️⃣ One-Hot Encoding (Dummy Encoding)**

### **Definition**

Creates **binary columns (0/1)** for each category.

### **Example**

| City      | Karachi | Lahore | Islamabad |
| --------- | ------- | ------ | --------- |
| Karachi   | 1       | 0      | 0         |
| Lahore    | 0       | 1      | 0         |
| Islamabad | 0       | 0      | 1         |

### **Advantages**

✔ No false ordering
✔ Most widely used

### **Disadvantages**

❌ Increases dimensions
❌ Curse of dimensionality

### **Best Used For**

* **Nominal data** (no order)
* Linear & distance-based models

---

## **3️⃣ Ordinal Encoding**

### **Definition**

Assigns numbers based on **natural order**.

### **Example**

| Rating    | Encoded |
| --------- | ------- |
| Poor      | 1       |
| Average   | 2       |
| Good      | 3       |
| Excellent | 4       |

### **Advantages**

✔ Preserves order
✔ Efficient

### **Disadvantages**

❌ Distance between categories may be misleading

### **Best Used For**

* Ordered categories

---

## **4️⃣ Binary Encoding**

### **Definition**

Categories → numbers → **binary format**.

### **Example**

| Category | Label | Binary |
| -------- | ----- | ------ |
| A        | 1     | 001    |
| B        | 2     | 010    |
| C        | 3     | 011    |
| D        | 4     | 100    |

### **Advantages**

✔ Fewer columns than One-Hot
✔ Efficient for high-cardinality data

### **Disadvantages**

❌ Slight information loss

### **Best Used For**

* Many unique categories (high cardinality)

---

## **5️⃣ Frequency Encoding**

### **Definition**

Replace categories with their **frequency count**.

### **Example**

| City      | Count |
| --------- | ----- |
| Karachi   | 500   |
| Lahore    | 300   |
| Islamabad | 200   |

### Advantages

✔ Very compact
✔ Fast

### Disadvantages

❌ Loses category meaning

### Best Used For

* Tree-based models

---

## **6️⃣ Target Encoding (Mean Encoding)**

### **Definition**

Replace categories with the **mean of the target variable**.

### Example

| City      | Avg Price |
| --------- | --------- |
| Karachi   | 70        |
| Lahore    | 55        |
| Islamabad | 65        |

### Advantages

✔ High predictive power

### Disadvantages

❌ Risk of **data leakage**
❌ Overfitting

### Best Used For

* Large datasets
* With cross-validation

---

## **7️⃣ Hash Encoding**

### **Definition**

Uses a **hash function** to map categories into fixed bins.

### Advantages

✔ Very fast
✔ Memory efficient

### Disadvantages

❌ Collisions possible

### **Best Used For**

* Very large datasets
* NLP pipelines

---

# 4. Encoding vs Scaling (Quick Difference)

| Aspect    | Encoding                      | Scaling               |
| --------- | ----------------------------- | --------------------- |
| Purpose   | Convert categories to numbers | Resize numeric values |
| Data Type | Categorical                   | Numerical             |
| Example   | City → 0,1,2                  | Salary → 0–1          |

---

# 5. Which Encoding Should You Use?

| Data Type         | Best Encoding            |
| ----------------- | ------------------------ |
| Binary (Yes/No)   | Label Encoding           |
| Nominal           | One-Hot Encoding         |
| Ordinal           | Ordinal Encoding         |
| High Cardinality  | Binary / Target Encoding |
| Tree-Based Models | Label / Frequency        |

---

# 6. Final Summary

✔ Encoding converts **categorical data into numeric form**
✔ ML models **cannot process text directly**
✔ Different encoding types suit **different data & models**
✔ Wrong encoding can **reduce accuracy**

# **Ordinal Encoding**

## What is Ordinal Encoding?


## Definition (Simple Words)

Ordinal Encoding assigns **integer values** to categories **according to their order**, not randomly.

---

## Example

### **Education Level (Ordered Data)**

| Education | Ordinal Encoded Value |
| --------- | --------------------- |
| Matric    | 0                     |
| Inter     | 1                     |
| Bachelor  | 2                     |
| Master    | 3                     |
| PhD       | 4                     |

✔ Here, the order makes sense:
Matric < Inter < Bachelor < Master < PhD

---

## **Why Do We Use Ordinal Encoding?**

### **1️⃣ To preserve ranking information**

Some categories have **relative importance or ranking**.

Example:

* Low < Medium < High
* Poor < Average < Good < Excellent

Ordinal Encoding keeps this information.

---

### **2️⃣ ML models understand order**

Models can learn:

* Higher encoded value = higher category

---

### **3️⃣ Memory efficient**

Uses **single column**, unlike One-Hot Encoding which creates many columns.

---

## **Another Example**

### **Customer Rating**

| Rating    | Encoded |
| --------- | ------- |
| Very Bad  | 1       |
| Bad       | 2       |
| Average   | 3       |
| Good      | 4       |
| Excellent | 5       |

---

## **Where Ordinal Encoding is Used**

✔ Survey responses
✔ Education levels
✔ Product ratings
✔ Risk levels (Low, Medium, High)

---

## **When NOT to Use Ordinal Encoding**

❌ **Nominal data** (no order)

Example:

* City names
* Colors
* Countries

Using ordinal encoding here creates **false relationships**.

---

## **Ordinal Encoding vs Label Encoding**

| Aspect          | Ordinal Encoding    | Label Encoding  |
| --------------- | ------------------- | --------------- |
| Order preserved | ✔ Yes               | ❌ No            |
| Used for        | Ordered data        | Any categorical |
| Risk            | Distance assumption | False order     |

---

## **Important Limitation**

⚠ Ordinal Encoding assumes:

* Distance between categories is equal
  But in reality:
* Difference between *Poor → Average* may not equal *Good → Excellent*

---

## **Python Example**

```python
from sklearn.preprocessing import OrdinalEncoder

data = [['Low'], ['Medium'], ['High']]
encoder = OrdinalEncoder(categories=[['Low', 'Medium', 'High']])
encoded = encoder.fit_transform(data)

print(encoded)
```

Output:

```
[[0.]
 [1.]
 [2.]]
```

---

## **Final Summary**

✔ Ordinal Encoding converts **ordered categories into numbers**
✔ Preserves ranking information
✔ Simple & memory efficient
✔ Should **only be used when order exists**

In [57]:
import numpy as np
import pandas as pd
from google.colab import drive

In [58]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [59]:
df=pd.read_csv("/content/drive/MyDrive/customer.csv")

In [60]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [61]:
df=df.iloc[:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [62]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [64]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [63]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [65]:
x=df.drop("purchased",axis=1)
y=df['purchased']

In [45]:
x

     review education
0   Average    School
1      Poor        UG
2      Good        PG
3      Good        PG
4   Average        UG
5   Average    School
6      Good    School
7      Poor    School
8   Average        UG
9      Good        UG
10     Good        UG
11     Good        UG
12     Poor    School
13  Average    School
14     Poor        PG
15     Poor        UG
16     Poor        UG
17     Poor        UG
18     Good    School
19     Poor        PG
20  Average    School
21  Average        PG
22     Poor        PG
23     Good    School
24  Average        PG
25     Good    School
26     Poor        PG
27     Poor        PG
28     Poor    School
29  Average        UG
30  Average        UG
31     Poor    School
32  Average        UG
33     Good        PG
34  Average    School
35     Poor    School
36     Good        UG
37  Average        PG
38     Good    School
39     Poor        PG
40     Good    School
41     Good        PG
42     Good        PG
43     Poor        PG
44  Average        UG
45     Poor        PG
46     Poor        PG
47     Good        PG
48     Good        UG
49     Good        UG

In [66]:
y

0      No
1      No
2      No
3      No
4      No
5     Yes
6      No
7     Yes
8      No
9     Yes
10    Yes
11    Yes
12     No
13     No
14    Yes
15     No
16    Yes
17    Yes
18     No
19    Yes
20    Yes
21     No
22    Yes
23     No
24    Yes
25     No
26     No
27     No
28     No
29    Yes
30     No
31    Yes
32    Yes
33    Yes
34     No
35    Yes
36    Yes
37    Yes
38     No
39     No
40     No
41    Yes
42    Yes
43     No
44     No
45    Yes
46     No
47    Yes
48    Yes
49     No
Name: purchased, dtype: object

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [69]:
x_train

     review education
25     Good    School
9      Good        UG
24  Average        PG
7      Poor    School
8   Average        UG
16     Poor        UG
34  Average    School
40     Good    School
42     Good        PG
30  Average        UG
46     Poor        PG
1      Poor        UG
13  Average    School
14     Poor        PG
35     Poor    School
10     Good        UG
22     Poor        PG
5   Average    School
11     Good        UG
38     Good    School
18     Good    School
45     Poor        PG
41     Good        PG
39     Poor        PG
4   Average        UG
33     Good        PG
3      Good        PG
0   Average    School
26     Poor        PG
23     Good    School
17     Poor        UG
29  Average        UG
2      Good        PG
19     Poor        PG
36     Good        UG
20  Average    School
31     Poor    School
37  Average        PG
47     Good        PG
32  Average        UG

In [70]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [71]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [72]:
x_train=oe.transform(x_train)

In [73]:
x_train

array([[2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.]])

In [74]:
y_train

25     No
9     Yes
24    Yes
7     Yes
8      No
16    Yes
34     No
40     No
42    Yes
30     No
46     No
1      No
13     No
14    Yes
35    Yes
10    Yes
22    Yes
5     Yes
11    Yes
38     No
18     No
45    Yes
41    Yes
39     No
4      No
33    Yes
3      No
0      No
26     No
23     No
17    Yes
29    Yes
2      No
19    Yes
36    Yes
20    Yes
31    Yes
37    Yes
47    Yes
32    Yes
Name: purchased, dtype: object